import db from "../config/db.js";
import { createGoogleMeetLink, hasGoogleMeetAutomationConfig } from "../utils/googleMeetService.js";
import {
  LIVE_SESSION_PROVIDER,
  LIVE_SESSION_STATUS,
  canTransition,
  isOneOf,
} from "../constants/lifecycle.js";

const getOwnedSession = async (sessionId, instructorId) => {
  const result = await db.query(
    `SELECT id, status, scheduled_at
     FROM live_sessions
     WHERE id = $1 AND instructor_id = $2`,
    [sessionId, instructorId]
  );
  return result.rows[0] || null;
};

const transitionSession = async (sessionId, instructorId, targetStatus) => {
  const session = await getOwnedSession(sessionId, instructorId);

  if (!session) {
    return { statusCode: 404, payload: { message: "Session not found" } };
  }

  if (!canTransition("liveSession", session.status, targetStatus)) {
    return {
      statusCode: 409,
      payload: { message: `Invalid transition from ${session.status} to ${targetStatus}` },
    };
  }

  const updated = await db.query(
    `UPDATE live_sessions
     SET status = $1, updated_at = NOW()
     WHERE id = $2 AND instructor_id = $3
     RETURNING *`,
    [targetStatus, sessionId, instructorId]
  );

  return { statusCode: 200, payload: updated.rows[0] };
};

const createLiveSession = async (req, res) => {
  const instructorId = req.user.userId;
  const { batchId } = req.params;
  const {
    title,
    description,
    scheduled_at,
    duration_minutes = 60,
    provider = LIVE_SESSION_PROVIDER.GOOGLE_MEET,
    join_url,
    host_url,
  } = req.body;

  if (!title || !scheduled_at) {
    return res.status(400).json({ message: "title and scheduled_at are required" });
  }

  const parsedScheduledAt = new Date(scheduled_at);
  if (Number.isNaN(parsedScheduledAt.getTime())) {
    return res.status(400).json({ message: "scheduled_at must be a valid datetime" });
  }

  if (parsedScheduledAt <= new Date()) {
    return res.status(400).json({ message: "scheduled_at must be in the future" });
  }

  const parsedDuration = Number(duration_minutes || 60);
  if (!Number.isInteger(parsedDuration) || parsedDuration < 15 || parsedDuration > 480) {
    return res.status(400).json({ message: "duration_minutes must be an integer between 15 and 480" });
  }

  if (!isOneOf(provider, LIVE_SESSION_PROVIDER)) {
    return res.status(400).json({ message: "Invalid live session provider" });
  }

  try {
    const ownership = await db.query(
      `SELECT b.id, b.timezone, b.status AS batch_status, b.start_date, b.end_date
       FROM batches b
       JOIN courses c ON b.course_id = c.id
       WHERE b.id = $1 AND c.instructor_id = $2`,
      [batchId, instructorId]
    );

    if (ownership.rows.length === 0) {
      return res.status(403).json({ message: "Not authorized to create session for this batch" });
    }

    const batch = ownership.rows[0];

    if (batch.batch_status === "completed") {
      return res.status(409).json({ message: "Cannot create a live session for a completed batch" });
    }

    if (batch.start_date && parsedScheduledAt < new Date(batch.start_date)) {
      return res.status(400).json({ message: "Session schedule cannot be before batch start_date" });
    }

    if (batch.end_date && parsedScheduledAt > new Date(batch.end_date)) {
      return res.status(400).json({ message: "Session schedule cannot be after batch end_date" });
    }

    let finalJoinUrl = join_url || "";
    let finalHostUrl = host_url || "";
    let autoGenerated = false;

    if (!finalJoinUrl && provider === LIVE_SESSION_PROVIDER.GOOGLE_MEET) {
      if (!hasGoogleMeetAutomationConfig()) {
        return res.status(400).json({
          message:
            "Google Meet automation is not configured. Provide join_url manually or configure Google OAuth env vars.",
        });
      }

      const meet = await createGoogleMeetLink({
        title,
        description,
        scheduledAt: scheduled_at,
        durationMinutes: parsedDuration,
        timezone: batch.timezone || "Asia/Kolkata",
      });

      finalJoinUrl = meet.meetLink;
      finalHostUrl = meet.meetLink;
      autoGenerated = true;
    }

    if (!finalJoinUrl) {
      return res.status(400).json({ message: "join_url is required when auto-generation is unavailable" });
    }

    const result = await db.query(
      `INSERT INTO live_sessions
       (batch_id, instructor_id, title, description, provider, scheduled_at, duration_minutes, join_url, host_url)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       RETURNING *`,
      [
        batchId,
        instructorId,
        title,
        description || null,
        provider,
        scheduled_at,
        parsedDuration,
        finalJoinUrl,
        finalHostUrl || finalJoinUrl,
      ]
    );

    return res.status(201).json({
      message: "Live session created",
      autoGenerated,
      session: result.rows[0],
    });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

const getInstructorSessions = async (req, res) => {
  const instructorId = req.user.userId;
  try {
    const result = await db.query(
      `SELECT ls.*, b.batch_name, c.title AS course_title
       FROM live_sessions ls
       JOIN batches b ON ls.batch_id = b.id
       JOIN courses c ON b.course_id = c.id
       WHERE ls.instructor_id = $1
       ORDER BY ls.scheduled_at DESC`,
      [instructorId]
    );
    return res.json(result.rows);
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

const startLiveSession = async (req, res) => {
  const instructorId = req.user.userId;
  const { sessionId } = req.params;
  try {
    const transition = await transitionSession(sessionId, instructorId, LIVE_SESSION_STATUS.LIVE);
    if (transition.statusCode !== 200) {
      return res.status(transition.statusCode).json(transition.payload);
    }

    return res.json({ message: "Session started", session: transition.payload });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

const endLiveSession = async (req, res) => {
  const instructorId = req.user.userId;
  const { sessionId } = req.params;
  try {
    const transition = await transitionSession(sessionId, instructorId, LIVE_SESSION_STATUS.COMPLETED);
    if (transition.statusCode !== 200) {
      return res.status(transition.statusCode).json(transition.payload);
    }

    return res.json({ message: "Session ended", session: transition.payload });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

const cancelLiveSession = async (req, res) => {
  const instructorId = req.user.userId;
  const { sessionId } = req.params;
  try {
    const transition = await transitionSession(sessionId, instructorId, LIVE_SESSION_STATUS.CANCELLED);
    if (transition.statusCode !== 200) {
      return res.status(transition.statusCode).json(transition.payload);
    }

    return res.json({ message: "Session cancelled", session: transition.payload });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

const getStudentSessions = async (req, res) => {
  const { userId } = req.user;
  try {
    const result = await db.query(
      `SELECT ls.id, ls.title, ls.description, ls.provider, ls.status, ls.scheduled_at, ls.duration_minutes,
              b.id AS batch_id, b.batch_name, c.id AS course_id, c.title AS course_title,
              u.name AS instructor_name,
              CASE WHEN sa.id IS NOT NULL THEN true ELSE false END AS is_present
       FROM live_sessions ls
       JOIN batches b ON ls.batch_id = b.id
       JOIN courses c ON b.course_id = c.id
       JOIN users u ON ls.instructor_id = u.id
       JOIN batch_enrollments be ON be.batch_id = b.id
       LEFT JOIN session_attendance sa ON sa.session_id = ls.id AND sa.user_id = $1
       WHERE be.user_id = $1 AND be.status = true
       ORDER BY ls.scheduled_at DESC`,
      [userId]
    );

    return res.json(result.rows);
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

const getStudentJoinLink = async (req, res) => {
  const { userId } = req.user;
  const { sessionId } = req.params;
  try {
    const result = await db.query(
      `SELECT ls.id, ls.title, ls.status, ls.scheduled_at, ls.duration_minutes, ls.join_url, ls.provider
       FROM live_sessions ls
       JOIN batch_enrollments be ON be.batch_id = ls.batch_id
       WHERE ls.id = $1 AND be.user_id = $2 AND be.status = true`,
      [sessionId, userId]
    );

    if (result.rows.length === 0) {
      return res.status(403).json({ message: "You are not allowed to access this session" });
    }

    return res.json(result.rows[0]);
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
};

export {
  createLiveSession,
  getInstructorSessions,
  startLiveSession,
  endLiveSession,
  cancelLiveSession,
  getStudentSessions,
  getStudentJoinLink,
};
